default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ideabox_rails_api
  password: 'password'

development:
  <<: *default
  database: ideabox_rails_api
  host: localhost

test:
  <<: *default
  database: ideabox_rails_api_test

production:
  <<: *default
  database: ideabox_rails_api_production
  password: <%= ENV['IDEABOX_RAILS_API_DATABASE_PASSWORD'] %>
